/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC2981Base } from "./ERC2981Base";
export type { ERC2981ContractWideRoyalties } from "./ERC2981ContractWideRoyalties";
export type { IERC2981Royalties } from "./IERC2981Royalties";
export type { LoveIsLoveCollection } from "./LoveIsLoveCollection";
