/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC2981Base__factory } from "./ERC2981Base__factory";
export { ERC2981ContractWideRoyalties__factory } from "./ERC2981ContractWideRoyalties__factory";
export { IERC2981Royalties__factory } from "./IERC2981Royalties__factory";
export { LoveIsLoveCollection__factory } from "./LoveIsLoveCollection__factory";
